// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestStatus = "queued" | "running" | "cancelling" | "completed" | "failed" | "cancelled" | "interrupted" | "owner_timed_out" | "lease_lost" | "turn_timed_out";
