// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalSignal = "cancel_confirmed" | "runtime_write_denied" | "writer_lease_lost" | "owner_lease_timed_out" | "turn_timed_out" | "interrupted" | "failed" | "completed";
